# Generated by Django 2.1 on 2018-09-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='gdate',
        ),
    ]
